name: Frontend Docker CI

on:
  push:
    branches:
      - 'Feature/frontend-*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: |
        pip install -r frontend/requirements.txt || pip install gradio requests pytest

    - name: Run unit tests
      run: |
        pytest tests/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and tag Docker image from frontend/
      run: |
        IMAGE_TAG=${GITHUB_REF##*/}
        IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/gradio-game-ui:$IMAGE_TAG
        docker build -t $IMAGE_NAME ./frontend
        echo "Built image: $IMAGE_NAME"

    - name: Push Docker image to Docker Hub
      run: |
        IMAGE_TAG=${GITHUB_REF##*/}
        IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/gradio-game-ui:$IMAGE_TAG
        docker push $IMAGE_NAME
        echo "Pushed image: $IMAGE_NAME"
